export const CATEGORIES: {[key: string]: string[]} = {
  animals: [
    'dog',
    'cat',
    'elephant',
    'lion',
    'tiger',
    'otter',
    'moose',
    'koala',
    'lemur',
    'badger',
    'gecko',
    'gerbil',
    'bison',
    'jaguar',
    'jaguar',
    'ferret',
    'donkey',
    'zebra',
    'puma',
    'sloth',
    'panda',
    'shrimp',
    'eagle',
    'iguana',
    'jaguar',
    'llama',
    'gopher',
    'marmot',
    'muskrat',
    'rabbit',
  ],
  cities: [
    'penang',
    'paris',
    'vienna',
    'oslo',
    'moscow',
    'tokyo',
    'berlin',
    'madrid',
    'odessa',
    'perth',
    'hamburg',
    'lima',
    'rome',
    'dublin',
    'athens',
    'seoul',
    'lisbon',
    'hanoi',
    'nairobi',
    'baku',
    'luanda',
    'dakar',
    'ljubljana',
    'brasília',
    'reykjavik',
    'tirana',
    'nassau',
    'lilongwe',
    'doha',
    'kigali',
  ],
  food: [
    'pizza',
    'burger',
    'taco',
    'sushi',
    'salad',
    'pasta',
    'fries',
    'ramen',
    'steak',
    'soup',
    'rice',
    'noodle',
    'toast',
    'bagel',
    'cheese',
    'scone',
    'waffle',
    'pancake',
    'donut',
    'croissant',
    'churro',
    'falafel',
    'curry',
    'shawarma',
    'hummus',
    'kebab',
    'gyoza',
    'dumpling',
    'bruschetta',
    'fajita',
  ],
};

export const getWordsByCategory = (category: string): string[] => {
  // get random 5 items from array
  if (!category) {
    return [];
  }
  const shuffled = CATEGORIES[category].sort(() => 0.5 - Math.random());
  return [...shuffled].slice(0, 5);
};

export const getCategories = (): string[] => {
  return Object.keys(CATEGORIES);
};
